<CommonComponentLabel>:
    halign: "center"

<MobileView>:
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 10
        Label:
            text: "Vista actual: Móvil"
            font_size: 20
            halign: "center"

<TabletView>:
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 20
        Label:
            text: "Vista actual: Tableta"
            font_size: 20
            halign: "center"

<DesktopView>:
    BoxLayout:
        orientation: "vertical"
        spacing: 30
        padding: 30
        Label:
            text: "Vista actual: Escritorio"
            font_size: 20
            halign: "center"
