name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-wheel python3-venv libncurses5
        pip install --upgrade pip
        pip install --user buildozer cython

    - name: Install buildozer deps
      run: |
        sudo apt install -y python3-pip python3-dev ffmpeg \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
          # Modificación: Se corrigieron los paquetes relacionados con GStreamer
          gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x \
          gstreamer1.0-alsa gstreamer1.0-pulseaudio
        sudo apt install -y libffi-dev libssl-dev
        sudo apt install -y liblzma-dev zlib1g-dev

    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KivyApp-APK
        path: bin/*.apk
