<MobileView>:
    MDLabel:
        text: "Vista Móvil"
        halign: "center"

<TabletView>:
    MDLabel:
        text: "Vista Tablet"
        halign: "center"

<DesktopView>:
    MDLabel:
        text: "Vista Escritorio"
        halign: "center"

<ResponsiveView>:
    mobile_view: mobile_view
    tablet_view: tablet_view
    desktop_view: desktop_view

    MobileView:
        id: mobile_view

    TabletView:
        id: tablet_view

    DesktopView:
        id: desktop_view
